### ISSUE TITLE
Input file extension matching on ffmpeg part

### ISSUE THREAD

**Issue by azmau** [ObronnaSosna/spotify-playlist-downloader#2]
Hi,

I had great fun hacking at your script to customize it and make it work on my Win machine. Great work!
However I ran into a problem because on `ffmpeg -i tmp/song*` it gives me `tmp/song*: Invalid argument` and its not due to the folder but because of the `*` in the file name, it cannot replace it with the actual extension. I tested by hardcoding it to `song.opus` and works fine on some cases but if the file downloaded is `song.m4a` for example of course it will not match anymore. I want to make it dynamic as  your intention seems to have been but my python beginner skills are not helping. 
I also tried using code from the youtube-dl part above `+ '" -o tmp/song.\%\(ext\)s'` but was not succesful. Any ideas?

Thanks a lot!

**Comment by ObronnaSosna** [comment]
I used this wildcard because youtube-dl downloads audio in a format that is stored on yt servers and i wanted to avoid compressing same file twice by using --audio-format in youtube-dl command.
Using wildcards in ffmpeg on windows seems buggy in general and i couldn't get it to work.
Windows doesn't like the way that script is passing arguments to ffmpeg and if title is more than one word it would crash because it would treat it as multiple output files.
After some googling i created workaround that should work:
 1. Create file ffmpeg_script.bat in script directory with
  `FOR %%A in (tmp/song*) DO ffmpeg.exe -i tmp/%%A -i tmp/thumb.jpg -map 0:0 -map 1:0 -id3v2_version 3 -y -metadata title=%1 -metadata artist=%2 -metadata album=%3 -b:a 320k %4` 
inside.
2. Comment out everything from line 99 to line 113
3. Add `system('ffmpeg_script "'+title+'" "'+artist+'" "'+album+'" "'+playlist_id+'/'+title+'_'+spotify_id+'.mp3"')` under.
Assuming you have ffmpeg binary in script directory or in PATH it should work.

**Comment by ObronnaSosna** [comment]
I added both ffmpeg_script.bat and modified spd.py to repo along with instructions.

**Comment by azmau** [comment]
With your changes the scripts works much better out of the box, none of my changes are needed anymore, thanks a lot!

However there still seems to be a problem when a playlist contains files of different formats that still doesn't work. Lets say youtube-dl downloads `song.opus` for the first item and in the end I get the corresponding `track1.mp3`. Moving to the second item in the playlist, it downloads `song.m4a` but SPD offers the first download to ffmpeg (`song.opus`) and I get a second file `track2.mp3` which is in fact a renamed copy of the first song. This is my 2 songs test playlist `4JlG261ZjK8CbLN8x970OB`, I hope you can use it to reproduce the problem, I'll keep it alive for awhile.

As a workaround I deleted the temporary files after each song was created using the batch file you provided but maybe you want/find a better/more elegant solution.

**Comment by ObronnaSosna** [comment]
You're right i absolutely forgot that when file extension is different it obviously will create another file and not overwrite it.
Added line to clear tmp before every download, this should fix it.

**Comment by azmau** [comment]
All good, thanks a lot!
